### ISSUE TITLE
Compilation failed error

### ISSUE THREAD

**Issue by Mirawaraxd** [0x23/WaveSimulator2D#2]
i`m not a programmer and proprably have bad english, but i follow instruction as i can and got that issue, please help.
my hardware:
[ geforge 1060 6gb
 intel i5 8400
 ssd 1tb
 16gb ram
]

(base) C:\Users\Mirawara\Desktop\WaveSimulator2D-main\source>python main.py
C:\Users\Mirawara\miniforge3\lib\site-packages\cupyx\jit\_interface.py:173: FutureWarning: cupyx.jit.rawkernel is experimental. The interface can change in the future.
  cupy._util.experimental('cupyx.jit.rawkernel')
libpng warning: iCCP: known incorrect sRGB profile
cub/detail/detect_cuda_runtime.cuh(39): warning: cuda_runtime_api.h: [jitify] File not found
../util_type.cuh(42): warning: cuda.h: [jitify] File not found
../../util_ptx.cuh(38): warning: util_type.cuh: [jitify] File not found
../../util_ptx.cuh(41): warning: util_debug.cuh: [jitify] File not found
../../thread/thread_load.cuh(40): warning: ../util_ptx.cuh: [jitify] File not found
---------------------------------------------------
--- JIT compile log for cupy_jitify_exercise ---
---------------------------------------------------
cub/util_cpp_dialect.cuh(143): warning #161-D: unrecognized #pragma

std/barrier(16): catastrophic error: #error directive: "CUDA synchronization primitives are only supported for sm_70 and up."

1 catastrophic error detected in the compilation of "cupy_jitify_exercise".
Compilation terminated.

---------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Mirawara\Desktop\WaveSimulator2D-main\source\main.py", line 77, in <module>
    simulate("../example_scenes/scene_lens_doubleslit.png",
  File "C:\Users\Mirawara\Desktop\WaveSimulator2D-main\source\main.py", line 57, in simulate
    simulator.update_field()
  File "C:\Users\Mirawara\Desktop\WaveSimulator2D-main\source\wave_simulation.py", line 55, in update_field
    laplacian = cupyx.scipy.signal.convolve2d(self.u, self.laplacian_kernel, mode='same', boundary='fill')
  File "C:\Users\Mirawara\miniforge3\lib\site-packages\cupyx\scipy\signal\_signaltools.py", line 352, in convolve2d
    return _correlate2d(in1, in2, mode, boundary, fillvalue, True)
  File "C:\Users\Mirawara\miniforge3\lib\site-packages\cupyx\scipy\signal\_signaltools.py", line 418, in _correlate2d
    return _st_core._direct_correlate(in1, in2, mode, in1.dtype, convolution,
  File "C:\Users\Mirawara\miniforge3\lib\site-packages\cupyx\scipy\signal\_signaltools_core.py", line 88, in _direct_correlate
    kernel(in1, in2, output)
  File "cupy\_core\_kernel.pyx", line 920, in cupy._core._kernel.ElementwiseKernel.__call__
  File "cupy\_core\_kernel.pyx", line 945, in cupy._core._kernel.ElementwiseKernel._get_elementwise_kernel
  File "cupy\_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy\_core\_kernel.pyx", line 728, in cupy._core._kernel._get_elementwise_kernel
  File "cupy\_core\_kernel.pyx", line 82, in cupy._core._kernel._get_simple_elementwise_kernel_from_code
  File "cupy\_core\core.pyx", line 2254, in cupy._core.core.compile_with_cache
  File "C:\Users\Mirawara\miniforge3\lib\site-packages\cupy\cuda\compiler.py", line 484, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "C:\Users\Mirawara\miniforge3\lib\site-packages\cupy\cuda\compiler.py", line 562, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "C:\Users\Mirawara\miniforge3\lib\site-packages\cupy\cuda\compiler.py", line 319, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "C:\Users\Mirawara\miniforge3\lib\site-packages\cupy\cuda\compiler.py", line 284, in _compile
    options, headers, include_names = _jitify_prep(
  File "C:\Users\Mirawara\miniforge3\lib\site-packages\cupy\cuda\compiler.py", line 233, in _jitify_prep
    jitify._init_module()
  File "cupy\cuda\jitify.pyx", line 212, in cupy.cuda.jitify._init_module
  File "cupy\cuda\jitify.pyx", line 233, in cupy.cuda.jitify._init_module
  File "cupy\cuda\jitify.pyx", line 209, in cupy.cuda.jitify._init_cupy_headers
  File "cupy\cuda\jitify.pyx", line 192, in cupy.cuda.jitify._init_cupy_headers_from_scratch
  File "cupy\cuda\jitify.pyx", line 264, in cupy.cuda.jitify.jitify
RuntimeError: Runtime compilation failed

**Comment by 0x23** [comment]
Looks like your Grafiks card is too old. Please try a newer nvidia GPU that supports shader model sm_70: 

#error directive: "CUDA synchronization primitives are only supported for sm_70 and up."
